# Разогрев

## Задание 1

Иногда, когда нужно создавать много однотипных лямбда функций, еще удобнее будет создать функцию, которая будет их генерировать.

Реализуйте функцию ``mod_checker(x, mod=0)``, которая будет **возвращать лямбда функцию** от одного аргумента ``y``, которая будет возвращать ``True``, если остаток от деления ``y`` на ``x`` равен ``mod``, и ``False`` иначе.

Если в ``return`` вашей функции написано выражение, отличное от лямбда функции - задание считается проваленным

**Sample:**

```python
mod_3 = mod_checker(3)

print(mod_3(3)) # True
print(mod_3(4)) # False

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4)) # True
```

In [ ]:
def mod_checker(x: int, mod =0) -> bool:
    """Return bool if y%x == mod"""
    return lambda y: y % x == mod

# Numpy

In [27]:
import numpy as np

## Задание 2
Напишите функцию, которая принимает один аргумент - ``n``. Функция должна создать нампаевскую матрицу размером ``(n, n)`` и залить ее шахматным узором. Порядок узора не имеет значения, важен общий паттерн.

**Sample:**
```python
chess_maze(8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```



In [ ]:

def chess_maze(n: int) -> np.array:
    """
    Функция принимает числоа n и строит матрицу(np.array) размером (n x n) и заливает
    ее шахматным узором.
    :param n: число вводимое для размера матрицы
    :return chess_board: матрицы размеров (n x n) с шахматным узором
    """

    chess_board = np.zeros((n,n),dtype=int)
    chess_board[::2,1::2] = 1
    chess_board[1::2,::2] = 1
    return chess_board


chess_maze(7)

## Задание 3
Напишите функцию, которая принимает 2 аргумента ``arr`` и ``exclude_values``. ``arr`` - это одномерный нампаевский массив, в котором необходимо поменять знак всем числам (инвертировать), которые есть в массиве ``exclude_values``. Действия необходимо делать прямо в исходном массиве, не создавая копий.

**Sample:**
```python
#Исходный вектор 
arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
 
my_func(arr, exclude_values)
array([ 0  1  2  3 -4 -5 -6 -7  8  9 10])
```

In [ ]:
# Option 1
arr = np.arange(100+1)
exclude_values = np.arange(10, 28)
def reverse_module(arr: np.array, exclude_values: np.array):
    """ 
    Функция для замены знака всем числам из массива arr, которые 
    встречаются в массиве exclude_values
    :param arr: исходный массив
    :param exclude_values: массив для нахождения чисел
    """
    for x in arr:
        if x in exclude_values:
            arr[x] = -abs(arr[x])
    return arr
    
reverse_module(arr, exclude_values)


## Задание 4
Напишите функцию, которая принимает одномерный положительный нампаевский массив и минимум 4 раза выводит на экран (функция ``print``) этот же массив, в котором у элементов оставлена только целая часть. Все >= 4 раза функция должна использовать разные методы для извлечения целой части.

**Sample:**
```python
#Исходный вектор 
arr = np.random.uniform(low=10, high=100,size=20)
#Исходный вектор arr:
arr
[99.54707368 49.26237526 80.50565073 10.10998238 16.39378916 60.64633657
 25.49637622 31.06574268 94.48636127 73.41204506 75.70638137 70.43830146
 72.28607422 40.59319738 57.85802554 35.39428061 55.25707514 48.00020145
 38.39449991 26.19085017]
 
my_func(arr)

[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99 49 80 10 16 60 25 31 94 73 75 70 72 40 57 35 55 48 38 26]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
```

В примере 5 выводов print из функции, просто чтобы были :)

In [304]:
def my_func(arr: np.array) -> np.array:
    """
    Функция в исходном массиве оставляет только целую часть элемента,
    и выводит новый массив четырьмя разными способами
    :param arr: исходный массив рандомный
    :arr1: функция на основе округления каждого элемента через 
    lambda  функция
    :arr2: приведение массива к типу данных int
    :arr3: метод trunc, отбрасывающий остаток
    :arr4: поэлементное приведение через цикл for
    """
    
    arr1 = list(map(lambda x: round(x), arr))
    arr1 = np.array([arr1])
    print(*arr1)
    arr2 = np.int8(arr)
    print(arr2)
    arr3 = np.trunc(arr)
    print(arr3)
    for i, elem in enumerate(arr):
        arr[i] = int(elem)
    print(arr)
arr = np.random.uniform(low=10, high=100,size=20)
my_func(arr)

[50 36 92 51 94 95 89 26 56 39 96 83 80 63 79 39 13 63 71 23]
[49 35 92 50 94 94 89 26 56 39 96 82 80 63 78 39 13 62 70 22]
[49. 35. 92. 50. 94. 94. 89. 26. 56. 39. 96. 82. 80. 63. 78. 39. 13. 62.
 70. 22.]
[49. 35. 92. 50. 94. 94. 89. 26. 56. 39. 96. 82. 80. 63. 78. 39. 13. 62.
 70. 22.]


## Задание 5
Напишите функцию, которая принимает два числа - ``N`` и ``p``. ``N`` - это размер стороны квадратной матрицы np.zeros, ``p`` - это количество индексов в матрице (p не превышает N*N), которые нужно заменить на случайные числа. Индексы и числа нужно выбирать случайно. Функция должна возвращать квадратную матрицу со стороной ``N``, в которой ровно ``p`` чисел заменены на случайные.

```python
my_func(N=6, p=4)

[[56.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [99.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 83.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   1.   0.]]
```

In [308]:
def my_func1(N: int, p: int) -> np.array:
    """
    Функция создает пустой массив размером (N*N), в котором в случайном
    порядке изменяет p количество индексов в массиве на случайные числа
    :param N: размер стороны квадратной матрицы
    :param p: количество индексов в матрице, требующих замены
    :return matric: финальный массив
    """
    if p > N*N: return "Wrong p, input p again!"
    matric = np.zeros((N,N))
    for i in range(p+1):
        matric[np.random.randint(1,N)][np.random.randint(1,N)] = np.random.randint(1,100,1)
    return matric
my_func1(10, 20)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 92.],
       [ 0.,  0., 93.,  0., 28., 40.,  0.,  0.,  0., 54.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 68., 95.],
       [ 0.,  0.,  7.,  0.,  0.,  0.,  0.,  0., 87.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 92.,  0.,  0.,  0.,  0.],
       [ 0., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 87.,  0.,  0.,  0.,  0.,  0.,  0., 60.,  0.],
       [ 0.,  0., 22.,  0.,  0.,  0.,  5.,  0.,  0.,  0.],
       [ 0.,  0., 30.,  0.,  0.,  0.,  0.,  0., 17.,  0.]])

# Pandas

In [309]:
import pandas as pd

# Задание 6

Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и четыре наблюдения в каждой колонке:

```
type value
B    18.

B    20.

C    10.

C    -10.
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

In [346]:
from numpy import int8

my_data = pd.DataFrame({
    'type': ['B','B','C','C'],
    'value': [18., 20., 10., -10.]
}
)
my_data.info()
#Размер my_data 192.0+ bytes
my_data['type'] = my_data['type'].astype('category')
my_data.info()
#Размер my_data 288.0 bytes
my_data['value'] = my_data['value'].astype(int8)
my_data.info()
#Размер my_data 260.0 bytes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   type    4 non-null      object 
 1   value   4 non-null      float64
dtypes: float64(1), object(1)
memory usage: 192.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    4 non-null      category
 1   value   4 non-null      float64 
dtypes: category(1), float64(1)
memory usage: 288.0 bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    4 non-null      category
 1   value   4 non-null      int8    
dtypes: category(1), int8(1)
memory usage: 260.0 bytes


# Задание 7
Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и десять тысяч (10 000) наблюдений в каждой колонке. В колонке ``type`` должно быть 10 уникальных значений.

```python
my_data.shape
____________
(10000, 2)
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

Во сколько раз уменьшился размер исходного датафрейма после выполнения этих двух операций?

In [348]:
type = pd.Series
my_data = pd.DataFrame({
    'type': ['B','B','C','C'],
    'value': [18., 20., 10., -10.]
}
)
my_data

type  value
0    B   18.0
1    B   20.0
2    C   10.0
3    C  -10.0

#### Для решения дальнейших задач мы будем использовать следующий датасет, загрузите его с помощью команды:

In [349]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')

In [350]:
df

V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
4     0  10.0  B -1.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[500 rows x 4 columns]

Примечание: все операции с исходным датафреймом должны быть ``inplace``. То есть исходный датафрейм в переменной ``df`` **должен** измениться

# Задание 8

В переменную с именем subset_1 сохраните только первые 19 строк и только 1 и 3 колонку.

В переменную с именем subset_2 сохраните все строки кроме 2, 3 и 18 и только 2 и 4 колонку.

In [384]:
subset_1 = df[['V1','V3']].head(19)
subset_2 = df[['V2','V4']].drop(labels=[2,3,18], axis = 0)

# Задание 9

В переменную subset_3 сохраните только те наблюдения, у которых значения переменной V1 строго больше 0, и значение переменной V3  равняется 'A'.

В переменную  subset_4  сохраните только те наблюдения, у которых значения переменной V2  не равняются 10, или значения переменной V4 больше или равно 1.

In [393]:
subset_3 = df[(df['V1']> 0) & (df['V3']=='A')]
subset_4 = df[(df['V2']!=10) | (df['V4']>=1)]



V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
5     2  11.0  A  0.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[447 rows x 4 columns]

# Задание 10
Добавьте следующие колонки в df:

1) V5 = V1 + V4
2) V6 = **натуральный** логарифм переменной V2

In [412]:
import math
df['V5'] = df['V1'] + df['V4']
df['V6'] = df['V2'].apply(math.log)

# Задание 11

Переименуйте колонки в df.

1) V1 -> session_value

2) V2 -> group

3) V3 -> time

4) V4 -> n_users

In [417]:
df.rename(columns={'V1': 'session_value', 'V2': 'group', 'V3': 'time', 'V4': 'n_users'}, inplace= True)
df

session_value  group time  n_users   V5        V6
0                2   13.0    B      1.0  3.0  2.564949
1               -1    7.0    B      1.0  0.0  1.945910
2                0   11.0    A      0.0  0.0  2.397895
3                2   11.0    A      2.0  4.0  2.397895
4                0   10.0    B     -1.0 -1.0  2.302585
..             ...    ...  ...      ...  ...       ...
495              1    8.0    A     -1.0  0.0  2.079442
496              3    8.0    A      1.0  4.0  2.079442
497             -1   11.0    B      2.0  1.0  2.397895
498              1   11.0    A      2.0  3.0  2.397895
499              0    8.0    B      1.0  1.0  2.079442

[500 rows x 6 columns]

# Задание 12
В датафрейме ``my_stat`` в колонке ``session_value`` замените все пропущенные значения на нули.

В колонке ``n_users`` замените все отрицательные значения на медианное значение переменной ``n_users`` (без учета отрицательных значений, разумеется).

In [418]:
my_stat = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')

In [420]:
mask = my_stat['session_value'].isna()


0    False
1     True
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: session_value, dtype: bool