In [ ]:
from beartype import beartype

#Reversed integer

Вам дано число целого типа ``a``. Вам необходимо написать функцию, которая принимает это число на вход, а на выход выдает целое число, цифры в котором записаны в обратном порядке.


**Sample Input 1:**

``
a = 123
``

**Sample Output 1:**

``321``

**Sample Input 2:**

``
a = 120
``

**Sample Output 2:**

``21``

**Sample Input 3:**

``
-123
``

**Sample Output 3:**

``321``

In [ ]:
a = int(input())
def reverse_number(a: int) -> int:
    """
    Функция, которая на вход принимает число a, а возвращает 
    число, цифры в котором записаны в обратном порядке.
    :param a: число входящее
    :return reverse: число в обратной последовательности
    """
    
    if a == 0: return 0
    a = abs(a) # Модуль числа
    res = str(a)
    while res.endswith('0'):
      res = res[:-1]
    revers = int(res[::-1])
    return revers

    
reverse_number(a)

    


#Выколотый квадрат


Напишите функцию, которая принимает единственное число ``n: int``. Это число определяет длину стороны квадрата. Функция должна нарисовать квадрат из звездочек, при этом звездочки должны быть только на ребрах квадрата, центр должен быть выколот.

**Sample Input 1:**

``
n = 5
``

**Sample Output 1:**
```
* * * * *
*       *
*       *
*       *
* * * * *

```

In [ ]:
# Вариант 1

n = int(input())
def empty_square (n: int) -> str:
    """ Draw empry square

    На вход подается число n, определяющее длину
    стороны квадрата. Задача функции нарисовать 
    квадрат из символов "*" с пустотой внутри
    : param n: int(n) - длина стороны квадрата
    : return empty square: возвращает нарисованный
    квадрат, сама функция ничего не возвращает.
    """
    for i in range(n):
        print()
        if i == 0 or i == n-1:
            for j in range(n):
                print("*", end=" ")
        else:
            for j in range(n):
                if j == 0 or j == n-1:
                    print('*', end=" ")
                else:
                    print(" ",end=" ")
    
empty_square(n)

#Пермутации

Вам дан массив с целыми числами ``nums``. Напишите функцию, которая принимает на вход данный массив и возвращает все возможные пермутации с данными числами. Возвращать массивы можно в любом порядке.

**Sample Input 1:**

``
nums = [1,2,3]
``

**Sample Output 1:**

``[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]``

**Sample Input 2:**

``
nums = [0,1]
``

**Sample Output 2:**

``[[0,1],[1,0]]``

**Sample Input 3:**

``
nums = [1]
``

**Sample Output 3:**

``[[1]]``

In [ ]:
# Вариант 1
import itertools
import numpy as np
from typing import List
nums = [1,2,3]
def permutations(nums: List) -> List:
  """
  Задача функции просчитать все возможные перестановки 
  входного массива и вернуть их в любой последовательности
  :param nums: на вход подается массив nums
  :return n: возращаем массив со всеми возможными перестановками
  """
  
  n = np.array(list(itertools.permutations(nums, len(nums))))
  return n
  
permutations(nums)

### Почти двойной факториал
Дано натуральное $N \leqslant 100$.  Выведите произведение всех чётных натуральных чисел, не превосходящих $N$.

In [ ]:
# Проверить через степпик
N = 25
n =[int(i) for i in range(1, N+1) if i % 2 == 0]

def almost_double_factorial(n: List) -> int:
  """
  Функция предназначена для произведения всех четных натуральных чисел
  (условимся,что 0 не является натуральным числом), не превосходящих N.
  :param n: список всех четных натуральных чисел от 1 до N(включительно)
  :return resusltat: число - произведение этих чисел.
  *Функция на основе рекурсии, при больших значениях N потребуется
  увеличить глубину рекурсии
  """
  
  if len(n) == 0: return 1
  resultat = n[0] * almost_double_factorial(n[1:])
  return resultat


N_double_fact = almost_double_factorial(n)
print(N_double_fact)

In [ ]:
N = 25
n = [int(i) for i in range(1,N+1) if i % 2 == 0]

N_double_fact = almost_double_factorial(n)

assert N_double_fact == 1961990553600, "Something is wrong! Please try again"


In [ ]:
N = 100
n = [int(i) for i in range(1,N+1) if i % 2 == 0]
N_double_fact = almost_double_factorial(n)
assert N_double_fact == 34243224702511976248246432895208185975118675053719198827915654463488000000000000, "Something is wrong! Please try again"

### Хитрая сортировка

Пусть у нас есть следующий список, в котором элементы -- tuple из строк:

``items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]``

Мы хотим отсортировать этот список по последней букве второго элемента каждого ``tuple``, т.е. получить такой список:

``sorted_items = [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]``.
Что нужно вставить вместо "###" в следующем выражении, чтобы получить сортировку?

``sorted_items = sorted(items, key=lambda x: ###)``

In [ ]:
items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

sorted_items = sorted(items, key = lambda x: x[1][-1])
print(sorted_items)
                      
assert sorted_items == [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')], \
"Something is wrong! Please try again"

### Еще строки

Вашей программе на вход подаются три строки ``s, a, b``, состоящие из строчных латинских букв.
За одну операцию вы можете заменить все вхождения строки ``a`` в строку ``s`` на строку ``b``.

Например, ``s = "abab", a = "ab", b = "ba"``, тогда после выполнения одной операции строка ``s`` перейдет в строку ``"baba"``, после выполнения двух и операций – в строку ``"bbaa"``, и дальнейшие операции не будут изменять строку ``s``.

Необходимо узнать, после какого минимального количества операций в строке ``s`` не останется вхождений строки ``a``. Если операций потребуется более 1000, выведите ``Impossible``.

Выведите одно число – минимальное число операций, после применения которых в строке ``s`` не останется вхождений строки ``a``, или ``Impossible``, если операций потребуется более 1000.

**Sample Input 1:**

``
ababa
a
b
``

**Sample Output 1:**

``1``

**Sample Input 2:**

``ababa
b
a``

**Sample Output 2:**

``1``

**Sample Input 3:**

``ababa
c
c``

**Sample Output 3:**

``0``

**Sample Input 4:**

``ababac
c
c``

**Sample Output 4:**

``Impossible``


In [ ]:
s,a,b = input().split()
def my_func(s: str, a: str, b:str) -> int:
    """ Minimum number of operations
    Функция подсчитывает вхождения количество вхождения строки а
    в строку s(если такие вхождения воообще есть), и заменяет все 
    вхождения на строку b. Подсчитывает количество необходимых
    операций и выводит их в результат в виде числа.
    :param s,a,b: подаваевые строки
    :cnt: счетчик количества операций
    """

    cnt = 0
    while a in s:
        count = s.count(a)
        s = s.replace(a, b, count)
        cnt += 1
        if cnt > 1000: return "Impossible"
    return cnt

my_func(s, a, b)

### Создание массивов
Дан массив $A[0,\ldots,N-1]$. Напишите функцию, принимающую один обязательный аргумент A и один опциональный аргумент ``erase``, по умолчанию равный 1. Возвратите массив $B[0,\ldots, N-1]$, где $B_i = A_0 + \ldots + A_{i}$ --- массив частичных сумм массива $A$, предварительно удалив из массива $B$ все элементы, равные erase. Постарайтесь сделать это за линейное время без использования Numpy.

In [ ]:
def cumsum_and_erase(A: List, erase = 1) ->List:
    """ 
    Функция, принимающая массив А, на основе которого создается
    массив В. Каждый новый элемент массива В состоит из сумм
    массива А(например эл.В2 = сумме А0+А1+А2). Затем из массива 
    В фильтруются все элементы, равные опциональному значению earse.
    : param A: входящий список(массив) чисел
    : return B: новый массив, созданный из частичных сумма массива А,
    предварительно обработанный
    """
    
    B =[]
    for i in range(len(A)):
        B.append(sum(A[:i+1]))
    B = list(filter(lambda x: x!=erase, B))
    return B

A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

### Обработка текста
Дан список текстов, слова в которых разделены пробелами (можно считать, что знаков препинания нет). Часть слов является "мусорными": в них присутствуют цифры и спецсимволы. Отфильтруйте такие слова из каждого текста. Используйте функции ``str.split``, ``str.isalpha``, ``str.join``, а также [генератор filter](http://pythonicway.com/python-functinal-programming).

In [ ]:

sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']
def process(sentences: List) -> List:
    """
    Функция для обработки текста и удаления цифр и спецсимволов
    во входящем списке строк.
    :param sentences: входящий список строк
    :return resultat: обработанный список строк
    """

    resultat = []
    for str in sentences:
        str =str.split()
        resultat.append(' '.join(filter(lambda x: x.isalpha(), str)))
    return resultat

print(process(sentences))

assert process(sentences) == ['thousand devils', 'My name is', 'Room costs'], \
"Something is wrong! Please try again"

#Расстояние Хэмминга

Вам даны две строки, ``a`` и ``b`` одинаковой длины. Необходимо посчитать расстояние Хэмминга между ними, которое определяется как количество символов, которые не совпадают между двумя строками в одинаковой позиции.

**Sample Input 1:**

```
a = 'AGCT'
b = 'ACGT'
hamming(a, b)
```

**Sample Output 1:**

``2``

In [ ]:
def hamming(a: str, b: str) -> int:
    """
    Функция рассчитывает расстояние Хэмминга между двумя
    одинаковыми строками(количество символов, не совподяющих
    между двумя строками в одинаковой позиции)
    :param a, b: принимает заданные строки
    :cnt: счетчик количества отличных символов в одной позиции
    """
    cnt = 0 
    for k, v in zip(a, b):
        if k != v:
            cnt += 1
    return cnt
a = input()
b = input()
hamming(a, b)
#assert hamming("AGCT", "ACGT") == 2

### Numpy

In [53]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [54]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.

a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim

print(np.ndim(a))
#2
print(np.ndim(b))
#2

# Используйте функцию shape, что она вывела? - Кортеж из количества строк и столбцов
print(np.shape(a))
# (100, 100)
print(np.shape(b))
# (100, 100)


# ========
# Ваш код здесь
# ========
print(a)
print(b)

2
2
(100, 100)
(100, 100)
[[0.47203233 0.94162188 0.34465046 ... 0.76234368 0.00494231 0.57442246]
 [0.98006472 0.51639486 0.03818667 ... 0.54829542 0.46507182 0.3333029 ]
 [0.22481212 0.93273778 0.71448734 ... 0.2715226  0.41603498 0.98403881]
 ...
 [0.86120193 0.18766586 0.65228683 ... 0.72228647 0.63905797 0.02086408]
 [0.12988386 0.79441531 0.1145861  ... 0.8892844  0.72718047 0.74091482]
 [0.99643514 0.5509301  0.19782942 ... 0.5730754  0.36132215 0.89051582]]
[[0.19952915 0.82336975 0.73183072 ... 0.81478937 0.82047808 0.39739615]
 [0.00871062 0.52622508 0.13498145 ... 0.9826063  0.32898227 0.73926609]
 [0.90787311 0.28077148 0.24085341 ... 0.90844151 0.7751742  0.57806437]
 ...
 [0.13169822 0.17495655 0.15089392 ... 0.35539509 0.22742852 0.21504147]
 [0.42757869 0.15404477 0.63532122 ... 0.44279046 0.01497825 0.76338999]
 [0.49891919 0.30215997 0.27413889 ... 0.05667837 0.74488699 0.47894286]]


Не знаю насколько разрешено было создавать базовые матрицы с помощью функций "с = np.ones" используя выражение "b = np.transpose(b)", но наверное, тут преследовались другие цели (перемножение матриц по векторам), которые в задачи отражены. 

In [55]:
# Вариант 1 - умножение на транспонированную матрицу
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 
    :def transpose: чтобы эффективно перемножить через zip транспонируем матрицу b
    :def umn_vec: перемножаем векторы матриц построчно
    :param c: новая матрица, итоговым размером size x size(зависит от матриц а и b) 
    """
    def umn_vec(vec_1, vec_2):
        """Сумма перемноженных элементов векторов"""
        return sum((x*y) for x,y in zip(vec_1, vec_2))
    def transpose(b):
        """Транспонирование матрицы b"""
        trans_b = [[0 for j in range(len(b[0:][0]))] for i in range(len(b[0][0:]))]
        return trans_b

    b = np.transpose(b)
    shape_c = (len(a[0:][0]),len(b[0][0:])) # размер новой матрицы
    c = np.zeros(shape_c)
    N = len(a[0][0:])
    for i in range(N):
        for j in range(N):
            vec_1 = a[i][0:]
            vec_2 = b[j][0:]
            c[i][j] = umn_vec(vec_1, vec_2)
    return c
mult(a,b)

array([[26.73748323, 26.05861816, 25.77840943, ..., 28.72577548,
        25.98652909, 24.84094308],
       [27.32849743, 27.05035042, 26.57848287, ..., 29.28141737,
        27.96153094, 24.13292372],
       [28.84109754, 25.68748807, 27.97634173, ..., 29.64786132,
        28.79274393, 26.02374828],
       ...,
       [25.73593841, 25.46664164, 25.4800441 , ..., 28.53869356,
        26.61046719, 22.86246997],
       [27.7616801 , 25.85218031, 25.73805412, ..., 29.23411508,
        25.37241169, 25.23589787],
       [23.80710754, 23.68665557, 25.16037223, ..., 28.60156516,
        26.58089616, 23.19441518]])

In [56]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    c = np.matmul(a,b)
    return c
np_mult(a,b)

array([[26.73748323, 26.05861816, 25.77840943, ..., 28.72577548,
        25.98652909, 24.84094308],
       [27.32849743, 27.05035042, 26.57848287, ..., 29.28141737,
        27.96153094, 24.13292372],
       [28.84109754, 25.68748807, 27.97634173, ..., 29.64786132,
        28.79274393, 26.02374828],
       ...,
       [25.73593841, 25.46664164, 25.4800441 , ..., 28.53869356,
        26.61046719, 22.86246997],
       [27.7616801 , 25.85218031, 25.73805412, ..., 29.23411508,
        25.37241169, 25.23589787],
       [23.80710754, 23.68665557, 25.16037223, ..., 28.60156516,
        26.58089616, 23.19441518]])

In [61]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 422 ms
Wall time: 584 ms


In [60]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 1 ms


In [62]:
# проверим корректность
assert np.allclose(np.array(M1), M2)